### ISSUE TITLE
JS redirection from URL to IP

### ISSUE THREAD

**Issue by llaumgui** [icescrum/iceScrum#29]
Hi,

I use iceScrum behind a Reverse proxy. I use the grails.serverURL configuration key but in my source code I can see:
~~~
var icescrum = {
                          grailsServer:"http://10.85.64.32:8080/icescrum",

                          push:{
                            enable:true,
                            websocket:false,
                            url:"http://10.85.64.32:8080/icescrum/stream/app"
                          },
                };
~~~

I think that grails.serverURL is not used...

**Comment by noullet** [comment]
Hi,

How did you configure your serverURL? 

What is the expected URL?

**Comment by llaumgui** [comment]
Hi,

My server URL is configured with my domain name:
~~~
grails.serverURL = https://mydomain/icescrum
~~~
And I use an Apache in reverse proxy. I display the site with the domain name but after few millisecond I have a JS redirection to my IP.

Thx

**Comment by noullet** [comment]
Hi,

If you update the configuration directly in the config.groovy file then you must follow its format. Here the URL is a string so it must be surrounded by double quotes.

**Comment by llaumgui** [comment]
Same result with double quote...

**Comment by vbarrier** [comment]
Hey did you reboot?

When the server is starting you can see in the log and/or in console which
and where the config.groovy file is. Could you check these information?

Cheers;

**Comment by mbenalaya** [comment]
Hello, 
I have the same problem.
Even after adding the param grails.serverURL = "http://mydomain/icescrum" to my config.groovy file. The javascript code remains unchanged:
var icescrum = {  
**grailsServer:"http://10.86.71.13:9095/icescrum", **
...
push:{
                            enable:true,
                            websocket:false,
                            **url:"http://10.86.71.13:9095/icescrum/stream/app"**
                          },
I can http://mydomain/icescrum without problems. However, the page is automatically redirected to the inaccessible http://10.86.71.13:9095/icescrum after browser time out.

I need help.
Thanks in advance,

**Comment by noullet** [comment]
Hello,

Did you restart after changing the configuration? 
Which version of iceScrum do you use? 
Do you use the .jar or the .war release?
Can you provide the location and content of the config.groovy file (don't forget to obfuscate passwords)?

**Comment by mbenalaya** [comment]
Hello
Thank you for your quick response.
- Yes, I restarted icescrum after changing the config.
- Last Version : R6#14.8 Pro Standalone
- I am using the .jar release.
 - Location of config.groovy: /root/.icescrum/config.groovy (The same mentioned on starting log)
- Content: of config.groovy:
grails.serverURL = "http://mydomain/icescrum" 
icescrum.login.retrieve.enable=false
icescrum.registration.enable=true
icescrum.project.import.enable=true
icescrum.gravatar.enable=false
dataSource.password="::icescrum::"
dataSource.driverClassName="com.mysql.jdbc.Driver"
icescrum.project.creation.enable=true
icescrum.alerts.enable=false
icescrum.project.private.default=false
icescrum.invitation.enable=false
icescrum.project.private.enable=true
dataSource.username="icescrum"
icescrum.baseDir="/root/icescrum"
icescrum.log.dir="logs"
icescrum.debug.enable=false
dataSource.url="jdbc:mysql://localhost:3306/icescrum?useUnicode=true&characterEncoding=utf8"
icescrum.project.export.enable=true

**Comment by vbarrier** [comment]
Could you also give us the command line used for jar?

**Comment by noullet** [comment]
Thanks for the details. The icescrum.jar release is a special case regarding hostname and port: they must be provided as parameters in the command used to start iceScrum. 

See https://www.icescrum.com/documentation/install-guide/#start

**Comment by mbenalaya** [comment]
I am using the following command:
> java -Xmx512M -XX:MaxPermSize=256m -jar icescrum host=10.86.71.13 port=9095
I configured a proxy on apache2:

<VirtualHost *:80>
ServerName mydomain
ProxyRequests Off
ProxyPreserveHost On
ProxyStatus On
Redirect /icescrum /icescrum/
ProxyPass /icescrum/ http://10.86.71.13:9095/icescrum/
ProxyPassReverse /icescrum/ http://10.86.71.13:9095/icescrum/
</VirtualHost>

Now when I enter http://mydomain:80 in my browser I can access to the icescrum interface. However in the google chrome developer frame I can see that all requests are redirected correctly. Only one targeting http://10.86.71.13:9095/icescrum/ which result in closing an error after time out. 

In addition when I checked the source code, I noticed that grail server contain the inaccessible address:
grailsServer:"http://10.86.71.13:9095/icescrum" 
url:"http://10.86.71.13:9095/icescrum/stream/app"

The question, how should I proceed to tell grailsserver to use "mydomain:80" instead of "10.86.71.13:9095". By the way I cannot make icescrum listen directly to "mydomain:80" because the port 80 is already in use by other servers.

**Comment by noullet** [comment]
Thanks for the additional information. 

Unfortunately the .jar release, while making it really easy to start iceScrum in a simple setup, does not allow the use of a reverse proxy for the moment. 

To leverage full customization you will need to install Tomcat (which is used under the hood in the .jar release). Here is our documentation for custom server install: https://www.icescrum.com/documentation/application-server/

**Comment by vbarrier** [comment]
Hello @mbenalaya , did you manage to make it work?

**Comment by mbenalaya** [comment]
Thank you for this clarification. 
I will test icescrum with tomcat this afternoon and get back to you.

**Comment by mbenalaya** [comment]
Hello,
Tomcat solved the proxy issue. However 2 notifications are displayed in the web interface:
1) No iceScrum Pro license detected..
2) "Error : Change your server URL"
"How to fix it? Your server url: http://localhost:8080/icescrum must be changed in order to let network users use your iceScrum server. Change this value on your admin panel"

I don't understand why "http://localhost:8080/icescrum" is displayed here knowing that I am using port 9595 as tomcat connector and "grails.serverURL="http://icescrum.etsi.org/icescrum" in config.groovy.

How to remove these two notification ?

Thanks
Mahdi

**Comment by noullet** [comment]
1) To remove this notification, you can simply close it by clicking on the "x" or you can alternatively enter a 14 trial license that you can get for free by registering on https://www.icescrum.com. This license enables extra features (including the admin panel) that you may be interested in and after 14 days you return automatically to the "community" features.

2) The URL displayed here is the one known by iceScrum as the serverURL, which indicates that your config.groovy file is not taken into account. Are you sure it is located in the home directory of the user who starts Tomcat? You can check which config.groovy file is used (if there is one) in the Tomcat standard output (catalina.out file).

**Comment by noullet** [comment]
Once it is fixed, I recommend that you switch to the R6#14.8 .war in order to benefit from the latest features and bug fixes.

**Comment by mbenalaya** [comment]
Hello,

You are right. I was working on the wrong config file. Now my server URI is correctly defined.
Using version 14.8 I was able to close the notification by clicking on the "x".

Icescrum is working like a charm.

Thank you so much for your help and prompt answers.
Best regards

**Comment by noullet** [comment]
Glad to know that it works!

By the way, we are based in Toulouse, feel free to contact us if you want to talk about iceScrum or if your are interested in iceScrum Pro, trainings, support...

**Comment by josechielli** [comment]
Hi from Germany!

Is it still no possible to force another domain in the config.groovy for grails? Different from the given as parameter to the .jar?

**Comment by josechielli** [comment]
I'm asking because I'm trying to deploy the jar in Azure Web Apps, and facing the same 127.0.0.1 redirect.

**Comment by vbarrier** [comment]
Hello did you correctly configure grails.serverURL ?

(Check documentation on icescrum.com :))

Regards;

**Comment by josechielli** [comment]
Yes, but as @noullet wrote, this could not work for the .jar deployment. I managed to change some other configs from groovy but not the one about the serverUrl...

**Comment by vbarrier** [comment]
Could you give us exactly the 2 urls? (the one expected / the one from jar)

**Comment by josechielli** [comment]
Expected: scrum4us.azurewebsites.net
The host and port for the jar is being dinamically assigned by Azure.

**Comment by vbarrier** [comment]
And this isn't possible on Azure? 
java -jar icescrum.jar host=scrum4us.azurewebsites.net port=80

**Comment by josechielli** [comment]
Not in Azure Web Apps. This is a sandbox and you cannot run on port 80. IIS handle the request to the port assigned to you dinamically. Something like this:

  <httpPlatform processPath="%JAVA_HOME%\bin\java.exe"
    arguments="-Djava.net.preferIPv4Stack=true -Dicescrum_config_location=%HOME%\.icescrum\config.groovy -Duser.home=%HOME% -Xmx512M -XX:MaxPermSize=256m -jar %HOME%\icescrum.jar port=%HTTP_PLATFORM_PORT%"

**Comment by josechielli** [comment]
I can access to http://mydomain/icescrum without problems. However, the page is automatically redirected to the inaccessible http://127.0.0.1:[someport]/icescrum/setup after few seconds

**Comment by vbarrier** [comment]
Ok so no simple solution for you without changing to classic tomcat server + war. icescrum.jar is designed to be use quickly and simply not with a proxy in front :(

**Comment by josechielli** [comment]
Yes, I thought so. No problem! Thanks anyway, I'll come back in case I have troubles with this other approach.
As a feedback It would de nice to advice this when offering the .jar as a deployment way! And much better if it could be adapted to this situation ;) :+1:
