### ISSUE TITLE
Icescrum loading failures on remote access

### ISSUE THREAD

**Issue by hermanfma** [icescrum/iceScrum#34]
After updating from icescrum 6 to 7, I started experiencing loading problems when accessing my [icescrum page](http://firasoft.ddns.net:3550/icescrum/#/) remotely.
The 3.8MB application-(...).js fails loading and the site gets stuck on the icescrum logo page. I can only keep refreshing the page until it works, but sometimes it simply doesn't.

Could you guys please check if there's an issue that causes this?

Thanks.

**Comment by noullet** [comment]
Any news? Otherwise I'll close the issue.
