### ISSUE TITLE
Build / Deployment instructions

### ISSUE THREAD

**Issue by sabatale** [icescrum/iceScrum#39]
Hello,

Thansk for your work, the app is actually really cool. However this is no documentation available on the GitHub / OpenSource side. Do you plan on providing developers with a documentation for development purpose? (at least how to build/deploy the app)

Thanks!

**Comment by noullet** [comment]
Hello,

Thank you for your kind feedback!

You will find a detailed answer to a similar question here: https://github.com/icescrum/iceScrum/issues/16#issuecomment-384620243

To summarize, just building iceScrum yourself is not really interesting as we already provide it as a portable executable .jar. It would be useful only if external contributors could also modify the source code in a meaningful way, which requires a lot of work from our side and unfortunately we are not there yet.

What did you have in mind?

**Comment by sabatale** [comment]
Hi,

Your answer from the other issue was pretty clear to me! Thanks again for your feedback!

**Comment by noullet** [comment]
You are welcome :)
