### ISSUE TITLE
User-Story Dependencies Issues after upgrading to v7.46

### ISSUE THREAD

**Issue by 0FiRE0** [icescrum/iceScrum#41]
After upgrading from v7.45 to v7.46, in User-Story, dependencies list for the parent User-Story, started to have double commas "," between the dependencies.

Snapshot below:
![image](https://user-images.githubusercontent.com/19993814/80279944-62302800-8709-11ea-9bef-41c54af71feb.png)

Also, in the case where the user is trying to add a new dependency, the list of other User-Stories to be linked to, became not accurate and not showing all other User-Stories. (After upgrading to 7.46)

**Comment by 0FiRE0** [comment]
Discovered that the User-Stories must be in a certain order in order for the other dependencies to appear in the list.

**Comment by vbarrier** [comment]
Only stories with an higher priority are shown. 

Is it the behavior that you are seeing? 

There were a bug before in the sandbox.

**Comment by 0FiRE0** [comment]
Thank you, for your feedback.
Correct, only User-Stories with higher ranking are showing up in the list of dependencies.

Then only the issue of having double comma "," between the dependencies remaining as shown in the picture above.

**Comment by vbarrier** [comment]
For the double comma, it appeared after a new dependence is added or after upgrade only

**Comment by 0FiRE0** [comment]
I think after the upgrade to v7.46
Previously, in v7.45, it remember was one comma "," only.

**Comment by vbarrier** [comment]
https://github.com/icescrum/iceScrum/commit/4fe046b5fab9d0c451b17eb47a3465cd41c20df1
