### ISSUE TITLE
Button + and - for "time spent" work, for a task in a closed sprint.

### ISSUE THREAD

**Issue by samuelroland** [icescrum/iceScrum#44]
Hello,
I potentially found a bug but i'm not sure. The picture is about a task in a closed sprint. And the buttons + and - are enabled and work (i can change the value). 
I think it shouldn't work like that because the time spent can not be changed after a sprint has been closed... So you can change a data that is not saved...
I think the buttons should be deleted or disabled, like for remaining time box.
![image](https://user-images.githubusercontent.com/47849646/81582933-edb7e300-93b0-11ea-94fa-8bf3c995b77a.png)
I hope you understand my explications and good continuation to you!

**Comment by noullet** [comment]
Hi,

Thank you for your report!

That is indeed a bug, but a minor one as changes made through these buttons are not really saved.

Anyway, it is fixed and the fix will be available in the next version (7.47).
