### ISSUE TITLE
Max chars error doesn't appear for an acceptance test description

### ISSUE THREAD

**Issue by samuelroland** [icescrum/iceScrum#46]
Hello
I found a bug (again) in the frontend. Just look at the picture below and see that i'm filling the field description in an acceptance test (i'm typing for update the text). The message "The input exceeds the maximum size of 1000 characters" doesn't appear before I click outside of the field (and disappear a very little time later) and button "Update" is disabled. The problem is that the message doesn't appear when the max is reached. And at start I didn't understand why the button was disabled because no error was displayed...

![acceptance test filling the description](https://user-images.githubusercontent.com/47849646/84514695-bbf5ad00-accb-11ea-88cf-c187bc5445d1.JPG)

But the bug is active only if you update the field twice. (manipulation: click one time and change the text, you will see the red error message, then click update after delete a piece of text. Then click a second time in the field to change the text and enter random text that reach more than the max of 1000 chars and see the bug described above...)

And the second problem is that when you reach the max and click outside, you just loose you entirely text of the description when you click inside the field again.

I hope you understand the problem i try to explain.

Thanks a lot and have a nice day.

**Comment by noullet** [comment]
Hi,

Thank you for your detailed report, we understood the issues!

Both issues are fixed in the latest version of iceScrum: 7.48.
