### ISSUE TITLE
cloud.icescrum.com is down

### ISSUE THREAD

**Issue by samuelroland** [icescrum/iceScrum#47]
It's down. Is it normal ? (update in run or something else ?)
you can check it here: https://downforeveryoneorjustme.com/cloud.icescrum.com
![image](https://user-images.githubusercontent.com/47849646/96787319-cea68e00-13f1-11eb-9da3-2f93b63fc7f2.png)
@vbarrier @noullet ?

**Comment by samuelroland** [comment]
It's up again...

**Comment by vbarrier** [comment]
Hello,

We have an network issue - working on it


<http://t.sidekickopen24.com/e1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-FdSD1CN4XyTvPS9PXKM1B0c-DNmkq103?t=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Ficescrum-technologies%2F&si=7000000000191787&pi=661ba681-68ca-40ce-a203-c086ab46a21a>

<http://t.sidekickopen24.com/e1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-FdSD1CN4XyTvPS9PXKM1B0c-DNmkq103?t=https%3A%2F%2Fwww.facebook.com%2Ficescrum&si=7000000000191787&pi=661ba681-68ca-40ce-a203-c086ab46a21a>

<http://t.sidekickopen24.com/e1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-FdSD1CN4XyTvPS9PXKM1B0c-DNmkq103?t=https%3A%2F%2Ftwitter.com%2Ficescrum&si=7000000000191787&pi=661ba681-68ca-40ce-a203-c086ab46a21a>
*Vincent
BARRIER*
CEO - Product Owner
+33 (0)9 52 91 10 10 <+33952911010>
+33 (0)6 49 88 39 78 <+33649883978>
www.icescrum.com - Get a demo!
<http://t.sidekickopen24.com/e1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-FdSD1CN4XyTvPS9PXKM1B0c-DNmkq103?t=https%3A%2F%2Fapp.hubspot.com%2Fmeetings%2Fvbarrier&si=7000000000191787&pi=661ba681-68ca-40ce-a203-c086ab46a21a>


Le mer. 21 oct. 2020 à 23:13, Samuel Roland <notifications@github.com> a
écrit :
