### ISSUE TITLE
The tasks screen flip when a task is selected

### ISSUE THREAD

**Issue by lascapi** [icescrum/iceScrum#51]
Hi, I'm going to try to describe a UX bug. 

When I'm in the tasks screen   
![Capture d’écran 2020-12-08 à 19 29 39](https://user-images.githubusercontent.com/6562527/101525588-cd262a80-398b-11eb-9d10-a4944897d4f9.png)

I select the first task   
![Capture d’écran 2020-12-08 à 19 22 26](https://user-images.githubusercontent.com/6562527/101525679-e929cc00-398b-11eb-87f5-520cbbc81b92.png)

Then I scrool down to the last 
![Capture d’écran 2020-12-08 à 19 22 59](https://user-images.githubusercontent.com/6562527/101525782-08285e00-398c-11eb-88f4-d3d44b2c67df.png)

When I select it, the scroll go up and I forget where I am = I don't see anymore the selected task
![Capture d’écran 2020-12-08 à 19 23 05](https://user-images.githubusercontent.com/6562527/101525871-3017c180-398c-11eb-92db-f8f84451c675.png)

I mean, as a user I want to see this
![Capture d’écran 2020-12-08 à 19 34 18](https://user-images.githubusercontent.com/6562527/101526046-6fdea900-398c-11eb-9c26-a69cfef09822.png)

It's just my opinion, but do you think it's a good idea? I use Icescrum every day and it's annoing for me. 

By the way, thank you very much to make Icescrum open source.

**Comment by noullet** [comment]
Hi Pascal,

What you describe is the intended result, what browser / OS / iceScrum versions do you use?

**Comment by lascapi** [comment]
Sorry, my bad! 

- Icescrum v7.46 Pro 
- Windows 10 2004
- Firefox 85.0a1 (2020-12-08) (64 bits), Iridium Version 2020.04 (Build officiel) (64 bits), Edge Version 87.0.664.55 (Version officielle) (64 bits)

**Comment by samuelroland** [comment]
Hi,
I have the same bug and didn't know how to describe it... so thanks to @lascapi.
To answer to @noullet, i use:
- IceScrum v7.51 Pro 
- Windows 10
- Firefox 83.0

**Comment by noullet** [comment]
Thanks to both of you. 

It seems to be related to Firefox, I will try to reproduce and I will keep you updated.

**Comment by noullet** [comment]
Thanks again for your report, it was not related to the browser, but rather due to small window size.

It is fixed and the fix will be available in the next version (7.52) in the upcoming weeks.
