### ISSUE TITLE
Bug with display of the product goal in the project configuration modal

### ISSUE THREAD

**Issue by samuelroland** [icescrum/iceScrum#54]
Hello,

I found a bug in the project configuration modal. The product goal is not empty but it looks like it's empty if the textarea is not on focus.

On hover (not focused), the text is invisible:
![2021-01-23_115033](https://user-images.githubusercontent.com/47849646/105576272-f5b68800-5d71-11eb-853a-6521c5fe7b20.png)

On focus the text appear:
![2021-01-23_115111](https://user-images.githubusercontent.com/47849646/105576273-f7804b80-5d71-11eb-8ae9-bde1f448b58a.png)
And it disappear again when the focus stop.

**Expected behavior**
The product goal should be displayed, because otherwise, we can believe that there is no value defined...

**I use**
- IceScrum v7.52 Pro
- Windows 10
- Firefox 84.0.2

**Comment by noullet** [comment]
Thanks for the detailed report! We actually found this bug and fixed it shortly before your report: https://github.com/icescrum/iceScrum/commit/fe602fb4e080b92b56b7338c060a218ac24094bc
